/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusBaseServer -a dbusbaseserver.h:dbusbaseserver.cpp ../../SpaceMeldCommon/dbusbase.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSBASESERVER_H_1411143166
#define DBUSBASESERVER_H_1411143166

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.spacemeld.device
 */
class DBusBaseServer: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.spacemeld.device")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.spacemeld.device\">\n"
"    <method name=\"getButtonCount\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"getDeviceName\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"getInterfaceName\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"getPath\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"response\"/>\n"
"    </method>\n"
"    <signal name=\"displacement\">\n"
"      <arg direction=\"out\" type=\"n\" name=\"axis0\"/>\n"
"      <arg direction=\"out\" type=\"n\" name=\"axis1\"/>\n"
"      <arg direction=\"out\" type=\"n\" name=\"axis2\"/>\n"
"      <arg direction=\"out\" type=\"n\" name=\"axis3\"/>\n"
"      <arg direction=\"out\" type=\"n\" name=\"axis4\"/>\n"
"      <arg direction=\"out\" type=\"n\" name=\"axis5\"/>\n"
"    </signal>\n"
"    <signal name=\"button\">\n"
"      <arg direction=\"out\" type=\"y\" name=\"buttonNumber\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"buttonDown\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    DBusBaseServer(QObject *parent);
    virtual ~DBusBaseServer();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    uchar getButtonCount();
    QString getDeviceName();
    QString getInterfaceName();
    QString getPath();
Q_SIGNALS: // SIGNALS
    void button(uchar buttonNumber, bool buttonDown);
    void displacement(short axis0, short axis1, short axis2, short axis3, short axis4, short axis5);
};

#endif
